// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyzbodeccgqcbskibbbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5emJvZGVjY2dxY2Jza2liYmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTkyNTEsImV4cCI6MjA3MDk5NTI1MX0.bZAkWOziDlF-NcdEk8NWjtDBxBc_ONTbJIwoBVFjz8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});